on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"