name: Publish

on:
  push:
    tags:
      - v*

jobs:
  images:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        base-image:
          - quay.io/c3os/core-opensuse:latest
          - quay.io/c3os/core-alpine:latest
        k3s-version:
          - v1.24.3+k3s1
          - v1.23.9+k3s1
          - v1.22.11+k3s2
          - v1.21.14+k3s1
        platform:
          - linux/amd64
          - linux/arm64
    env:
      REGISTRY: quay.io
      REGISTRY_USER: ${{ secrets.QUAY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - run: echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin $REGISTRY
      - run: env | grep ACTIONS_ID_TOKEN_REQUEST > .env
      - run: env | grep REGISTRY >> .env
      - run: earthly --ci --push --platform=${{ matrix.platform }} +docker --K3S_VERSION=${{ matrix.k3s-version }} --BASE_IMAGE=${{ matrix.base-image }}
      - run: earthly --ci +cosign --K3S_VERSION=${{ matrix.k3s-version }} --BASE_IMAGE=${{ matrix.base-image }}

